<?php 

// compliments, opposite of it, cuss words
const FRIENDS = [
    'vikram' => 'https://tenor.com/bVVdt.gif',
    'dilli' => 'https://tenor.com/tFiRvWexPl8.gif',
    'amar' => 'https://tenor.com/bXex0.gif',
];

const ENEMIES = [
    'rolex' => 'https://tenor.com/bVTYk.gif',
    'anbu' => 'https://tenor.com/bCL3F.gif',
    'sandhanam' => 'https://tenor.com/bTXcU.gif'
];

const COMPLIMENTS = [
    'beautiful',
    'kind',
    'talented',
    'smart',
    'friendly',
    'creative',
    'amazing',
    'awesome',
    'generous',
    'helpful',
    'intelligent',
    'funny',
    'caring',
    'thoughtful',
    'charming',
    'inspiring',
    'wonderful',
    'gracious',
    'compassionate',
    'excellent',
    'fantastic',
    'lovely',
    'outstanding',
    'remarkable',
    'terrific',
    'phenomenal',
    'brilliant',
    'impressive',
    'exceptional',
    'majestic',
    'sensational',
    'astounding',
    'breathtaking',
    'stunning',
    'marvelous',
    'glorious',
    'amiable',
    'amiable',
    'graceful',
    'elegant',
    'fabulous',
    'superb',
];

const OPPOSITES = [
    'ugly',
    'mean',
    'untalented',
    'not very bright',
    'unfriendly',
    'uncreative',
    'ordinary',
    'awful',
    'selfish',
    'unhelpful',
    'unintelligent',
    'not funny',
    'indifferent',
    'thoughtless',
    'uncharming',
    'uninspiring',
    'awful',
    'heartless',
    'poor',
    'dreadful',
    'ugly',
    'mediocre',
    'average',
    'terrible',
    'horrible',
    'dull',
    'unimpressive',
    'ordinary',
    'unexceptional',
    'mundane',
    'unimpressive',
    'unimpressive',
    'unimpressive',
    'unimpressive',
    'unimpressive',
    'unimpressive',
    'unimpressive',
    'unimpressive',
    'unimpressive',
    'unimpressive',
    'unimpressive',
];


const EMOTIONS = [
    'happy' => '😄',
    'sad' => '😢',
    'angry' => '😡',
    'surprised' => '😲',
    'love' => '❤️',
    'confused' => '😕',
    'excited' => '😃',
    'worried' => '😟',
    'calm' => '😌',
    'grateful' => '🙏',
    'bored' => '😑',
    'relieved' => '😌',
    'hopeful' => '🤞',
    'fearful' => '😨',
    'content' => '😊',
    'shy' => '😳',
    'disgusted' => '🤢',
    'embarrassed' => '😳',
    'proud' => '😎',
    'tired' => '😴',
];